import { AccountOutline, ArrowDown, CartOutline, ChartFilled, ChartOutline, CheckbookOutline, CheckboxOutline, CheckboxOutlineBlank, CheckCircle, CheckCircleOutline, CheckSmall, CreditCard, CurrencyExchange, Domain, EnterpriseOutline, Error, ErrorOutline, Finance, Google, Info, InfoOutline, Logo, MonetizationOutline, Money, Notification, OrdersOutline, PaymentOutline, Person, RadioChecked, RadioUnchecked, SavingsOutline, SellOutline, Settings, ShoppingBagOutline, StoreFontOutline, TrackChanges, Vector, Warning, WarningOutline } from "./components";

export const Icons = {
  ArrowDown,
  AccountOutline,
  CartOutline,
  ChartFilled,
  ChartOutline,
  CheckbookOutline,
  CheckboxOutline,
  CheckboxOutlineBlank,
  CheckSmall,
  CreditCard,
  CurrencyExchange,
  Domain,
  EnterpriseOutline,
  Finance,
  Google,
  Logo,
  MonetizationOutline,
  Money,
  Notification,
  OrdersOutline,
  PaymentOutline,
  Person,
  SavingsOutline,
  SellOutline,
  Settings,
  ShoppingBagOutline,
  StoreFontOutline,
  TrackChanges,
  Vector,
  RadioChecked,
  RadioUnchecked,
  CheckCircle,
  CheckCircleOutline,
  Error,
  ErrorOutline,
  Info,
  InfoOutline,
  Warning,
  WarningOutline
} as const